export const tweetsAtKimKataguiri = [
  'Sigam o @mblivrenews',
  'Intervalo do debate no @programapanico, mandem comentários com a hashtag #DebateNoPanico',
  'Pessoal de Indaiatuba e região, estou agora, debatendo ao vivo, na Rádio @clip_fm. Sintonize em 88.7!',
  'Em instantes entro ao vivo no @programapanico para debater com Gilberto Dimenstein, acompanhem!',
  'Começando agora entrevista do Haddad no Jornal Nacional',
  'E já começamos com corrupção na pauta com a pergunta da Renata Vasconcellos',
  'Jingle da @carinavitral é “Dim dimdim, vote na Carina, sim!” Isso diz bastante sobre o objetivo de sua candidatura. Ah, e música com pedido de voto antes do dia 16 é crime eleitoral, viu? A cara de pau é tanta que nem disfarça. Alô @mpsp_oficial, campanha antecipada pode?',
  'Bom dia pessoal! Quem for de Marília ou região, estarei hoje às 16h ao vivo na Rádio Campestre, e as 19h30 na UNOPAR em uma palestra sobre Reforma Política, Liberalismo e Conservadorismo.',
  'Incrível! Enquanto o Arthur @mamaefalei queria falar sobre o maior problema fiscal do país, a reforma da previdência, @IsaPennaPsol tentava esquivar e falar sobre MACONHA. Percebe-se quem leva o debate a sério. #PingaFogo',
  'Bonner expondo que o PT aparelhou o judiciário, mostrando que a tese de golpe e perseguição política contra Lula e o partido dos trabalhadores.',
  'Renata pressionando Haddad. Sangue nos olhos.',
  'Com a narrativa de que o Lula é inocente, Haddad nunca vai admitir a corrupção do PT. Vai enrolar até o fim sem responder.',
  'Caramba, que patada do Bonner. Haddad tentando acusar a Globo e levou uma boa.',
  'A ex-vereadora @IsaPennaPsol gastou em 1 mês mais do que o @FernandoHoliday em seu mandato inteiro. O exemplo deve vir de cima, assim como o Holiday que cortou 50% de verba de gabinete, 95% da verba auxiliar, dispensou carro oficial, etc. #PingaFogo',
  'Não basta mais de 200 páginas de autos e provas contra Lula (só sobre o triplex claro), o Judiciário errou. Ata.',
  'Não estou conseguindo publicar no meu Facebook =( ta tudo bugado, me ajuda tio Marquinhos Zuckerberg!',
  '“Ah, o judiciário errou ao prender Lula” Então duas instâncias seguidas erraram ao prender Lula? Poupe-me né?',
  'Um punhado de militantes da extrema-esquerda fez conluio com monopólios da imprensa para calar as várias correntes da direita por meio da censura nas redes. Ver a hashtag #DireitaSegueDireita nos assuntos mais comentados do Twitter mostra que a armadilha não funcionou direito...',
  'Bolsonaro faz muito bem em reforçar o compromisso com Paulo Guedes e ser honesto em relação à limitação imposta pelo Congresso Nacional em relação à aprovação das propostas. Segue bem. #BolsonaroNoJornalNacional',
  'Bolsonaro começou bem. É fato que, apesar de estar há mais de duas décadas na política, ele não pode ser comparado aos velhos caciques corruptos de Brasília #BolsonaroNoJornalNacional',
  'Bonner citando todos os petistas presos e questionando sobre a quadrilha petista. Não deve ter media training que supere uma pergunta do Bonner.',
  'Será que Bolsonaro tocou no tema casamento de propósito? Rs#BolsonaroNoJornalNacional',
  'Todos sabem que sou contra todo tipo de privilégios, mas lançar notinha sem citar nome de nenhum deputado só para ganhar clique em cima da indignação da população é baixaria. Quem acusa tem o dever de dar nome aos bois. Amadorismo (para dizer o mínimo) da @RevistaCrusoe',
  'Entraram no campo do Bolsonaro. Kit gay no material escolar só faz seus eleitores reforçarem ainda mais sua convicção. #BolsonaroNoJornalNacional',
  'A militância pró-aborto está em alvoroço sobre a decisão do senado argentino em recusar o projeto de lei que visava a descriminalização desta violência no país. Ir na direção contrária destas pessoas é mais uma prova de que estamos no caminho certo ao defender o direito à vida.',
  '“O PT tem uma lista imensa de investigados e presos” BONNER, William',
  '“A PEC dignificou o trabalho dos domésticos”. Mentira descarada, a pec foi um desastre e só jogou os profissionais na informalidade e no desemprego. #BolsonaroNoJornalNacional',
  'Resolução 71, Art. 1o. parágrafo 1o., do #CNJ, “proíbe que o plantão judiciário aprecie reiteração de pedido já apreciado no órgão judicial de origem ou em plantão anterior, nem à sua reconsideração ou reexame”',
  'Quero dar meus parabéns para o deputado eleito @ViniciusPoit, que começou uma campanha contra o aumento de salário imoral que está sendo proposto na Câmara. Tem todo meu apoio! Precisamos de toda ajuda possível, ajudem a divulgar essa iniciativa. #aumentonao',
  'A esquerda, que sempre fugiu de debates com medo de ser desmascarada (alô, @marciatiburi, Jean Wyllys e @Ticostacruz), agora tem a cara de pau de falar #VemProDebate. Fácil chamar alguém que mal tem forças para andar pra debater. Querem debate? Eu topo. E aí, @Haddad_Fernando?',
  'Quem ta reclamando da minha meia é fascista, machista e homofobico',
  'Eventos como esta audiência pública do STF sobre o aborto fazem aparecer milhares de "ativistas dos direitos humanos" militando contra o Direito a vida. Faz sentido pra você? #AbortoÉCrime',
  'Velha falácia da desigualdade de salários entre homens e mulheres. Apesar da patada da apresentadora, Bolsonaro se saiu bem: se já está na lei, o que o Executivo pode fazer? Cabe ao MPT fiscalizar. #BolsonaroNoJornalNacional',
  'Engraçado o Haddad falando de poupar mas deixou um rombo bilionário na prefeitura.',
  'Passada a convenção, já é oficial: sou candidato a deputado federal. Conto com a ajuda de vocês!',
  'A narrativa que transformou Marielle Franco em mártir, infelizmente não serviu para expor com a mesma urgência, o assassinato da PM Juliane dos Santos. Assim como Marielle, ela também era negra e homossexual, mas a esquerda preferiu o silêncio à revolta.',
  'Haddad gaguejou, obviamente nervoso. Bonner ainda pegou ele na mentira. Não tá fácil pra ele hein?',
  'Sorteio dos gabinetes foi hoje. Fiquei com o do @sibamachado13. Não sei se fico triste pelo azar ou se fico feliz porque ele perdeu a eleição.',
  'Bom dia pra quem chegou no aeroporto com uma hora de antecedência por causa da Apple. E ainda tem gente que diz que o capitalismo é bom. A burguesia manipula até o horário pra fazer o proletariado dormir menos',
  'Tão falando que eu apareci na Globo, confere? Não faz sentido, não participei de nenhuma entrevista nos últimos dias. Foi de passagem, tipo quando o Arthur apareceu apanhando no Fantastico? Hahaha',
  'Resposta sobre segurança pública irretocável. Policial que, no meio da ação, mata o criminoso que porta arma ostensivamente, deve ser condecorado, sim. #BolsonaroNoJornalNacional',
  '“”A cada x horas um LGBT morre”. No Brasil, TODO MUNDO morre. Temos mais de 60 mil homicídios por ano. O crime não tem preferência. #BolsonaroNoJornalNacional',
  'Jornalista japonês perguntou se eu gosto de anime. Disse que só  lembrava de alguns, tipo One piece, death note, boku no hero, nanatsu no taizai, bleach, code geass, fullmetal, DBZ, gurren lagan,steins gate, one punch man, death parade, e SNK. O cara arregalou o olho e sorriu.',
  'Msm petistada que está chamando o Bolsonaro de frouxo foge de um moleque de 22 anos. Vergonha, hein? Cadê os trocentos anos d vida pública e realizações políticas dos quais vocês tanto se orgulham? E o diálogo democrático? Petista só é macho com qm tá no hospital? #HaddadArregao',
  'Que tal subir #HaddadArregao pra ver se ele se manifesta?',
  'Estou no curso para os deputados eleitos, mas achei estranho que até agora o professor não ensinou nem a cuspir no coleguinha, nem a bloquear a sessao comendo marmita na cadeira do presidente',
  '"Com 30 mil de salario, recebendo 13o, 14o e 15o durante 30 anos não dá pra comprar 3 apartamentos". Entenderam p q a esquerda sempre leva o país pro buraco? Como deputado federal, defendo educação financeira ja no ensino básico. Vamos mudar essa triste realidade. #TretaNoPânico',
  '#EleNaoEMeuPresidente exatamente o mesmo rancor anti-democratico da eleição do Trump: "not my president". Felizmente, hashtags e textoes lacradores não têm o poder de acabar com a democracia. Bolsonaro foi eleito. Sobrevivemos a 13 anos de PT. Respeitem as instituições.',
  'Obrigado, meus queridos. O trabalho continua. Agora, é entrar com o pé na porta e acabar com o totalitarismo petista.',
  'Marco Aurelio soltou Lula no ultimo dia antes do recesso apenas em busca de holofotes. É um irresponsável, um militante de toga. Em um país sério, isso terminaria na cadeia. A ADC já tem data marcada para ir ao pleno, decisão absurda, só para tocar fogo no país.'
]
